spring:
  application:
    name: auth-service

server:
  port: ${PORT}

  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=${DB_ENCRYPT};trustServerCertificate=${DB_TRUST_CERT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE}
      minimum-idle: ${DB_MIN_IDLE}
      connection-timeout: ${DB_TIMEOUT}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: ${JPA_FORMAT_SQL}
        jdbc:
          batch_size: ${JPA_BATCH_SIZE}
        order_inserts: true
    show-sql: ${JPA_SHOW_SQL}

  liquibase:
    change-log: classpath:liquibase-changelog/db_auth-changelog.xml
    enabled: ${LIQUIBASE_ENABLED}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: ${REDIS_TIMEOUT}
    lettuce:
      pool:
        max-active: ${REDIS_POOL_MAX}
        max-idle: ${REDIS_POOL_IDLE}
        min-idle: ${REDIS_POOL_MIN}

  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        enabled: ${CONSUL_ENABLED}
        service-name: ${spring.application.name}
        health-check-interval: ${CONSUL_HEALTH_INTERVAL}
        health-check-path: ${CONSUL_CHECK_PATH}
        prefer-ip-address: ${PREFER_IP_ADDRESS}
        register: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS}
  endpoint:
    health:
      show-details: ${ACTUATOR_SHOW_DETAILS}
  health:
    readiness:
      enabled: ${REDIS_READINESS}
logging:
  level:
    com.ecommerce.campus.auth-service: ${LOG_LEVEL_APP}
    org.springframework.security: ${LOG_LEVEL_SECURITY}
    org.hibernate.SQL: ${LOG_LEVEL_SQL}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"