spring:
  application:
    name: auth-service

  liquibase:
    change-log: classpath:/liquibase-changelog/db_auth-changelog.xml
    enabled: true
    clear-checksums: true

  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_AUTH_NAME};encrypt=${DB_ENCRYPT};trustServerCertificate=${DB_TRUST_CERT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE}
      minimum-idle: ${DB_MIN_IDLE}
      connection-timeout: ${DB_TIMEOUT}

server:
  port: ${PORT_AUTH}

## Separate SpringDoc configuration
springdoc:
  enable-actuator: false
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
  show-actuator: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

#JPA
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: ${JPA_FORMAT_SQL}
        jdbc:
          batch_size: ${JPA_BATCH_SIZE}
        order_inserts: true
    show-sql: ${JPA_SHOW_SQL}


  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    timeout: ${REDIS_TIMEOUT}
    lettuce:
      pool:
        max-active: ${REDIS_POOL_MAX}
        max-idle: ${REDIS_POOL_IDLE}
        min-idle: ${REDIS_POOL_MIN}

  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        enabled: ${CONSUL_ENABLED}
        service-name: ${spring.application.name}
        health-check-interval: ${CONSUL_HEALTH_INTERVAL}
        health-check-path: ${CONSUL_CHECK_PATH}
        prefer-ip-address: ${PREFER_IP_ADDRESS}
        register: true
      config:
        enabled: false

#Actuator
management:
#  server:
#    port: ${PORT_AUTH}
  endpoints:
    web:
      exposure:
        include: always #${ACTUATOR_ENDPOINTS}
      endpoints:
        web:
          base-path: /actuator/health
  endpoint:
    health:
      show-details: ${ACTUATOR_SHOW_DETAILS}
  health:
    readiness:
      enabled: ${REDIS_READINESS}
logging:
  level:
    com.ecommerce.campus.auth-service: DEBUG
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.boot.context.config: DEBUG
    liquibase: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

debug: true
