spring:
  # H2 Database for development
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Relaxed JWT security for development
auth:
  jwt:
    secret: dev-secret-key-256-bits-minimum-for-hmac-sha256-algorithm
    access-token-expiration: PT1H     # 1 hour
    refresh-token-expiration: P7D     # 7 days

logging:
  level:
    root: INFO
    com.ecommerce.campus.auth: DEBUG