spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=auth_db;encrypt=false;trustServerCertificate=true
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: false
        jdbc:
          batch_size: 25
        order_inserts: true
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: 1000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        service-name: ${spring.application.name}
        health-check-interval: 10s
        health-check-path: /actuator/health

server:
  port: ${PORT:8081}

jwt:
  secret: ${JWT_SECRET:mySecretKey123!@#mustBe256BitsLongForHS256}
  access-token-expiration: 900000 # 15 minutes
  refresh-token-expiration: 604800000 # 7 days

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ecommerce.campus.auth-service: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"