spring:
  application:
    name: api-gateway
  cloud:
    consul:
      discovery:
        enabled: ${CONSUL_ENABLED}
        service-name: ${spring.application.name}
        health-check-interval: ${CONSUL_HEALTH_INTERVAL}
        health-check-path: ${CONSUL_CHECK_PATH}
        prefer-ip-address: ${PREFER_IP_ADDRESS}
        register: false
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: ${GATEWAY_ENABLED}
          lower-case-service-id: ${GATEWAY_LOWERCASE}

server:
  port: ${PORT_GATEWAY}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ecommerce.campus.api-gateway: INFO
    org.springframework.cloud.consul: DEBUG