spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: ${GATEWAY_ENABLED}
          lower-case-service-id: ${GATEWAY_LOWERCASE}
    consul:
      host: ${CONSUL_HOST}
      port: ${CONSUL_PORT}
      discovery:
        enabled: ${CONSUL_ENABLED}
        service-name: ${spring.application.name}
        health-check-interval: ${CONSUL_HEALTH_INTERVAL}
        health-check-path: ${CONSUL_CHECK_PATH}
        prefer-ip-address: ${PREFER_IP_ADDRESS}
        register: false

server:
  port: ${PORT_GATEWAY}

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS}
  endpoint:
    health:
      show-details: ${ACTUATOR_SHOW_DETAILS}

logging:
  level:
    com.ecommerce.campus.api-gateway: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"