spring:
  application:
    name: api-gateway
  cloud:
    consul:
      discovery:
        enabled: ${CONSUL_ENABLED}
        service-name: ${spring.application.name}
        health-check-interval: ${CONSUL_HEALTH_INTERVAL}
        health-check-path: ${CONSUL_CHECK_PATH}
        prefer-ip-address: ${PREFER_IP_ADDRESS}
        register: false
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: ${GATEWAY_ENABLED}
          lower-case-service-id: ${GATEWAY_LOWERCASE}
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          order: 1
        - id: not-found-route
          uri: forward:/not-found
          predicates:
            - Path=/api/**
          filters:
            - SetStatus=404
          order: 999
server:
  port: ${PORT_GATEWAY}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.ecommerce.campus.api-gateway: INFO
    org.springframework.cloud.consul: DEBUG